"""Update Posts Table

Revision ID: c6d9c0c35e32
Revises: c53a2db4df56
Create Date: 2024-04-16 22:30:06.446215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d9c0c35e32'
down_revision: Union[str, None] = 'c53a2db4df56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), nullable=False))
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
