"""Fix User Table

Revision ID: f53c3b68fd53
Revises: c6d9c0c35e32
Create Date: 2024-04-16 23:29:03.903522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53c3b68fd53'
down_revision: Union[str, None] = 'c6d9c0c35e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
